# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Arvio
email: l@arv.io
description: I hope you have something in your life you could put in DNS for the maximum TTL.
baseurl: '' # the subpath of your site, e.g. /blog
url: http://www.arv.io # the base hostname & protocol for your site, e.g. http://example.com
github_username: lateio
twitter_username: _lateio
logo: /assets/img/logo.png

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-extlinks
  - jekyll-redirect-from
  - jekyll-sitemap

# Removed categories from permalinks
permalink: /:year/:month/:day/:title:output_ext

# Settings for jekyll-extlinks
extlinks:
    attributes:
        rel: nofollow
        target: _blank
    rel_exclude:
        - www.arv.io

# jekyll-seo-tag
social:
    name: Lauri Moisio
    links:
        - http://github.com/lateio
        - http://twitter.com/_lateio
author: Lauri Moisio
defaults:
    - scope:
        path: ''
      values:
        image: /assets/img/logo.png
twitter:
    username: _lateio
    card: summary
webmaster_verifications:
    bing: 'D8AF3360EB5696042102A31C635929EA'
    yandex: '0354ee548452fd9a'
lang: en_FI

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
